export type Tool = 'estimate' | 'table' | 'graph' | 'algebra';

export interface Drill {
  id: number;
  zone: string;
  title: string;
  prompt: string;
  tool: Tool;
  why: string;
  setup: string;
  question: string;
  options: string[];
  answer: number;
  explanation: string;
  expression?: string;
  xValues?: number[];
  range?: [number, number, number, number];
  estimate?: string;
}

export const toolInfo: Record<Tool, { label: string; symbol: string; cue: string }> = {
  estimate: { label: 'Estimate', symbol: '≈', cue: 'Use when scale or plausibility matters more than exact digits.' },
  table: { label: 'Table', symbol: '▦', cue: 'Use to inspect repeated values, steps, or discrete patterns.' },
  graph: { label: 'Graph', symbol: '⌁', cue: 'Use to see shape, crossings, turning points, or behavior.' },
  algebra: { label: 'Algebra', symbol: '=', cue: 'Use to preserve exact relationships or verify a claim.' },
};

export const drills: Drill[] = [
  { id: 1, zone: 'Orientation', title: 'Size before precision', prompt: 'A workshop buys 49 packs at £21 each. Before calculating exactly, check the likely total.', tool: 'estimate', why: 'Round both factors to friendly numbers to expose the scale quickly.', setup: 'Round 49 → 50 and 21 → 20.', question: 'Which is the most useful estimate?', options: ['About £100', 'About £1,000', 'About £10,000'], answer: 1, estimate: '50 × 20 = 1,000', explanation: 'The estimate says the exact answer should be near £1,000. If a calculator later says £10,029, you know to inspect the entry.' },
  { id: 2, zone: 'Orientation', title: 'See repeated growth', prompt: 'You want to compare 2ˣ with 3x for whole-number inputs from 0 to 5.', tool: 'table', why: 'A short table makes discrete comparisons explicit without hiding the individual values.', setup: 'Inspect 2^x at x = 0, 1, 2, 3, 4, 5.', question: 'At which first whole-number x after 0 does 2ˣ exceed 3x?', options: ['x = 2', 'x = 4', 'x = 5'], answer: 2, expression: '2^x', xValues: [0, 1, 2, 3, 4, 5], explanation: 'At x = 5, 2⁵ = 32 while 3x = 15. Tables are especially useful when the permitted inputs are discrete.' },
  { id: 3, zone: 'Orientation', title: 'Find the crossings', prompt: 'Locate where y = x² − 4 crosses the horizontal axis.', tool: 'graph', why: 'Crossings are spatial facts; a graph makes both candidates visible at once.', setup: 'Plot x^2 - 4 from −5 to 5.', question: 'Where are the two x-intercepts?', options: ['−4 and 4', '−2 and 2', '0 and 4'], answer: 1, expression: 'x^2 - 4', range: [-5, 5, -6, 12], explanation: 'The curve crosses y = 0 at x = −2 and x = 2. A graph locates them; algebra can verify them exactly.' },
  { id: 4, zone: 'Orientation', title: 'Check an identity', prompt: 'Someone expands (x + 3)² as x² + 9. Test whether that statement is always true.', tool: 'algebra', why: 'Expansion preserves the exact relationship and reveals the missing term.', setup: '(x + 3)(x + 3)', question: 'Which expansion is correct?', options: ['x² + 9', 'x² + 3x + 9', 'x² + 6x + 9'], answer: 2, explanation: 'Multiplying every term gives x² + 3x + 3x + 9 = x² + 6x + 9.' },
  { id: 5, zone: 'Scale & sense', title: 'Bracket a root', prompt: 'Without reaching for exact decimals, place √50 between nearby whole numbers.', tool: 'estimate', why: 'Nearby perfect squares bracket the value with almost no computation.', setup: '7² = 49 and 8² = 64.', question: 'Which statement is best?', options: ['√50 is just above 7', '√50 is near 7.5', '√50 is just below 8'], answer: 0, estimate: '49 < 50 < 64, so 7 < √50 < 8', explanation: 'Because 50 is only one above 49, √50 is only a little above 7 (about 7.07).' },
  { id: 6, zone: 'Scale & sense', title: 'Read a constant rate', prompt: 'A tank starts with 10 L and gains 3 L each minute. Inspect the first four minutes.', tool: 'table', why: 'A table makes the fixed increase from one step to the next easy to audit.', setup: 'Use y = 3x + 10 for x = 0, 1, 2, 3.', question: 'How much is in the tank at minute 3?', options: ['13 L', '19 L', '30 L'], answer: 1, expression: '3*x + 10', xValues: [0, 1, 2, 3], explanation: 'At x = 3, y = 3(3) + 10 = 19. Each row increases by 3.' },
  { id: 7, zone: 'Scale & sense', title: 'Compare two shapes', prompt: 'Find the positive point where y = x² and y = 2x + 3 meet.', tool: 'graph', why: 'Plotting both relationships shows how many intersections exist and where to investigate.', setup: 'The combined equation is x^2 - 2*x - 3 = 0.', question: 'What is the positive x-coordinate?', options: ['1', '2', '3'], answer: 2, expression: 'x^2 - 2*x - 3', range: [-4, 5, -6, 14], explanation: 'The difference curve crosses zero at x = −1 and x = 3, so the positive intersection is x = 3.' },
  { id: 8, zone: 'Scale & sense', title: 'Test a proposed solution', prompt: 'A note claims x = 6 solves 4x − 5 = 19. Verify it efficiently.', tool: 'algebra', why: 'Direct substitution checks the exact claim without re-solving the whole problem.', setup: 'Replace x with 6 on the left.', question: 'What does the left side become?', options: ['19', '24', '29'], answer: 0, explanation: '4(6) − 5 = 24 − 5 = 19, so the proposed value passes the check.' },
  { id: 9, zone: 'Patterns', title: 'Sense-check a percentage', prompt: 'A £79 item is discounted by 18%. Estimate the amount saved.', tool: 'estimate', why: 'Rounding 18% to 20% and £79 to £80 gives a quick reasonableness check.', setup: '20% of £80 = one fifth of £80.', question: 'Which is the sensible estimate?', options: ['About £1.60', 'About £16', 'About £40'], answer: 1, estimate: '0.2 × 80 = 16', explanation: 'The exact saving is £14.22, close enough to the £16 estimate to look plausible.' },
  { id: 10, zone: 'Patterns', title: 'Track compound change', prompt: 'A quantity starts at 100 and grows 10% per step. Inspect the first three steps.', tool: 'table', why: 'A table prevents compound growth from being mistaken for equal additions.', setup: 'Use y = 100 × 1.1^x.', question: 'What is the value at step 2?', options: ['110', '120', '121'], answer: 2, expression: '100*1.1^x', xValues: [0, 1, 2, 3], explanation: 'After two multiplications by 1.1, the value is 121—not 120. The increase itself grows.' },
  { id: 11, zone: 'Patterns', title: 'Spot a forbidden input', prompt: 'Inspect y = 1/x near x = 0 and decide what happens there.', tool: 'graph', why: 'The separated branches make the discontinuity and opposing directions visible.', setup: 'Plot 1/x from −5 to 5.', question: 'Which describes x = 0?', options: ['The graph crosses at 0', 'The function is undefined there', 'The function equals 1 there'], answer: 1, expression: '1/x', range: [-5, 5, -6, 6], explanation: 'Division by zero is undefined. The plot has two branches and no point at x = 0.' },
  { id: 12, zone: 'Patterns', title: 'Preserve equivalence', prompt: 'Simplify (6x²)/(3x) while keeping track of the original restriction.', tool: 'algebra', why: 'Symbolic cancellation reveals both the simpler form and the condition that made cancellation legal.', setup: 'Divide coefficients by 3 and cancel one factor of x.', question: 'Which is complete?', options: ['2x for every x', '2x, with x ≠ 0', '2, with x ≠ 0'], answer: 1, explanation: 'The expression simplifies to 2x, but the original denominator means x = 0 was never allowed.' },
  { id: 13, zone: 'Bounds & behavior', title: 'Bound an area', prompt: 'A rectangular room is 5.9 m by 4.1 m. Estimate its floor area before ordering materials.', tool: 'estimate', why: 'Friendly dimensions reveal the rough area and guard against unit or decimal errors.', setup: 'Round to 6 m by 4 m.', question: 'What is the useful estimate?', options: ['About 10 m²', 'About 24 m²', 'About 60 m²'], answer: 1, estimate: '6 × 4 = 24 m²', explanation: 'The exact area is 24.19 m², so 24 m² is an excellent scale check (but not a purchasing allowance).' },
  { id: 14, zone: 'Bounds & behavior', title: 'Recognize quadratic change', prompt: 'Inspect y = x² at consecutive whole numbers and compare first differences.', tool: 'table', why: 'Rows and differences expose the signature pattern of a quadratic.', setup: 'Use x = 0, 1, 2, 3, 4.', question: 'What are the first differences?', options: ['1, 1, 1, 1', '1, 3, 5, 7', '2, 4, 6, 8'], answer: 1, expression: 'x^2', xValues: [0, 1, 2, 3, 4], explanation: 'The outputs 0, 1, 4, 9, 16 have differences 1, 3, 5, 7. Their second difference is constant.' },
  { id: 15, zone: 'Bounds & behavior', title: 'Locate a turning point', prompt: 'Find the highest point of y = −(x − 2)² + 4.', tool: 'graph', why: 'A turning point is a feature of shape; the graph gives its location and height together.', setup: 'Plot -(x - 2)^2 + 4.', question: 'What is the maximum point?', options: ['(−2, 4)', '(2, −4)', '(2, 4)'], answer: 2, expression: '-(x - 2)^2 + 4', range: [-4, 7, -10, 7], explanation: 'The downward-opening curve peaks at (2, 4). The form already hints at that point; the graph confirms it.' },
  { id: 16, zone: 'Bounds & behavior', title: 'Solve and reverse-check', prompt: 'Solve 3(x − 2) = 15, then verify by substitution.', tool: 'algebra', why: 'Inverse operations give an exact value; substitution catches sign and arithmetic mistakes.', setup: 'Divide by 3, then add 2.', question: 'Which value passes the check?', options: ['x = 3', 'x = 5', 'x = 7'], answer: 2, explanation: 'x = 7 gives 3(7 − 2) = 3 × 5 = 15.' },
  { id: 17, zone: 'Transfer line', title: 'Catch a division slip', prompt: 'Estimate 198 ÷ 6.1 before using exact division.', tool: 'estimate', why: 'Compatible numbers provide a quick target for the quotient.', setup: 'Use 198 ≈ 198 and 6.1 ≈ 6.', question: 'Which is closest?', options: ['About 3.3', 'About 33', 'About 330'], answer: 1, estimate: '198 ÷ 6 = 33', explanation: 'The exact result is about 32.46, consistent with the estimate. A misplaced decimal would stand out.' },
  { id: 18, zone: 'Transfer line', title: 'Approach from both sides', prompt: 'Inspect 1/x at small positive and negative x-values near zero.', tool: 'table', why: 'Chosen input values let you compare the two one-sided behaviors explicitly.', setup: 'Use x = −1, −0.5, −0.1, 0.1, 0.5, 1.', question: 'As x approaches 0 from the positive side, what happens?', options: ['Values become large and positive', 'Values approach 0', 'Values become large and negative'], answer: 0, expression: '1/x', xValues: [-1, -0.5, -0.1, 0.1, 0.5, 1], explanation: 'For 0.5, 0.1, and still smaller positive x, the outputs 2, 10, … grow without bound.' },
  { id: 19, zone: 'Transfer line', title: 'Compare rates visually', prompt: 'Compare y = 0.5x and y = 2x. Which rises faster from left to right?', tool: 'graph', why: 'Slope is visible as steepness when both lines use the same axes.', setup: 'Plot their difference: 2*x - 0.5*x.', question: 'Which line is steeper?', options: ['y = 0.5x', 'They are equally steep', 'y = 2x'], answer: 2, expression: '1.5*x', range: [-5, 5, -10, 10], explanation: 'A rise of 2 per step is steeper than a rise of 0.5. Shared axis scales are essential for this visual comparison.' },
  { id: 20, zone: 'Transfer line', title: 'Check a rearranged formula', prompt: 'From d = rt, a learner writes t = d/r. Verify using d = 150 km and r = 60 km/h.', tool: 'algebra', why: 'Substitution verifies both the rearrangement and the units.', setup: 't = 150 ÷ 60 hours.', question: 'What time results?', options: ['0.4 h', '2.5 h', '90 h'], answer: 1, explanation: '150 ÷ 60 = 2.5 hours. The units also check: km ÷ (km/h) = h.' },
];

export const quiz = [
  { prompt: 'You only need to know whether 598 × 0.21 is nearer 12, 120, or 1,200.', answer: 'estimate' as Tool, why: 'Round to 600 × 0.2 = 120.' },
  { prompt: 'You need the outputs of a recurrence at the first eight whole-number steps.', answer: 'table' as Tool, why: 'A table preserves each discrete step.' },
  { prompt: 'You need to find how many times two continuous curves cross.', answer: 'graph' as Tool, why: 'A graph reveals the number and rough location of intersections.' },
  { prompt: 'You need to prove two rearranged formulas are exactly equivalent.', answer: 'algebra' as Tool, why: 'Symbolic steps preserve exact equivalence.' },
  { prompt: 'A calculator gives 0.0049 for 24.5 ÷ 5. You want a ten-second plausibility check.', answer: 'estimate' as Tool, why: '25 ÷ 5 ≈ 5, so the display is implausible.' },
  { prompt: 'You need the peak and overall shape of a quadratic model.', answer: 'graph' as Tool, why: 'A graph shows the turning point in the context of the whole curve.' },
];
